

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArtifactoryMaven@2
  inputs:
    mavenPomFile: 'maven-example/pom.xml'
    goals: 'install'
    artifactoryResolverService: 'JoeySaaS'
    targetResolveReleaseRepo: 'libs-release'
    targetResolveSnapshotRepo: 'libs-snapshot'
    artifactoryDeployService: 'JoeySaaS'
    targetDeployReleaseRepo: 'libs-release'
    targetDeploySnapshotRepo: 'libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

- task: ArtifactoryPublishBuildInfo@1
  inputs:
    artifactoryService: 'JoeySaaS'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

